Add reviews
kirpinev/java-filmorate pull request #15
Opened 2023-01-28 01:07 UTC by MaricTheirin

Реализована функциональность «Отзывы»

2023-01-28 10:51 UTC, Prysya requested changes

2023-01-28 10:51 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    }
Можно добавить аннотацию @RequiredArgsConstructor и убрать конструктор (Как сейчас сделано во всех сервисах)
@Qualifier тут не особо нужен, сейчас всего 1 бин который автоматом подтянется

2023-01-28 10:51 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +    }
Аналогично можно добавить @RequiredArgsConstructor для единообразия

2023-01-28 10:51 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +        } catch (NullPointerException e) {
Процитирую моего ревьюера с предыдущего спринта

> Обработка `NPE` не являтеся хорошей практикой, более корректно было бы пересмотреть логику таким образом, чтобы это исключение не могло быть выброшено)

2023-01-28 10:51 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +    }
Во всем проекте маппер вынесен в отдельный класс, вынеси тоже пожалуйста :)

2023-01-28 10:51 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReviewRating/ReviewRatingDbStorage.java
> +
Аналогично можно добавить @requiredargsconstructor для единообразия

2023-01-28 10:51 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReviewRating/ReviewRatingDbStorage.java
> +    }
Во всем проекте маппер вынесен в отдельный класс, вынеси тоже пожалуйста :)

2023-01-28 10:51 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        log.debug("Запуск проверок отзыва");
А что будет с кейсом если filmReview будет null ?)

2023-01-28 11:50 UTC, kirpinev requested changes

2023-01-28 11:50 UTC, kirpinev commented on src/main/resources/schema.sql
> +    review_id int generated by default as identity primary key,
По идее рецензия на фильм от человека может быть только одна, значит возможно можно сделать составной ключ из film_id и user_id

2023-01-28 15:18 UTC, romaozna commented on src/main/resources/schema.sql
> +    review_id int generated by default as identity primary key,
В этом случае наша бд не будет в третьей нормальной форме, так как чтобы найти оценку нужно будет джоинить еще таблицу с фильмами

2023-01-28 15:23 UTC, kirpinev commented on src/main/resources/schema.sql
> +    review_id int generated by default as identity primary key,
Добро

2023-01-28 15:27 UTC, kirpinev approved these changes

2023-01-28 23:16 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    }
Реализовано

2023-01-28 23:16 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +    }
Реализовано

2023-01-28 23:41 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +        } catch (NullPointerException e) {
Не совсем понимаю как здесь выкрутиться, т.к. NPE может выбрасывать KeyHolder. Чуть изменил код, но не уверен, что смогу принципиально что-то изменить

2023-01-28 23:54 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +    }
Реализовано

2023-01-28 23:54 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReviewRating/ReviewRatingDbStorage.java
> +
Реализовано

2023-01-28 23:55 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReviewRating/ReviewRatingDbStorage.java
> +    }
Реализовано

2023-01-28 23:58 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        log.debug("Запуск проверок отзыва");
По идее обработка до этого момента в принципе не дойдёт если filmReview == null, т.е. вешать доп. проверку большого смыла нет.

2023-01-29 10:35 UTC, Prysya requested changes

2023-01-29 10:35 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +        } catch (NullPointerException e) {
Вот как пример из директоров, я кстати даже недавно узнавал у своих сеньоров с работы, проверка на `NPE` реально не очень хорошая практика )

```java
    @Override
    @ResponseStatus(HttpStatus.CREATED)
    public Director createDirector(Director director) {
        String sqlQuery = "insert into directors(name) values (?)";

        KeyHolder keyHolder = new GeneratedKeyHolder();

        jdbcTemplate.update(connection -> {
            PreparedStatement stmt = connection.prepareStatement(sqlQuery, new String[] {"director_id"});
            stmt.setString(1, director.getName());
            return stmt;
        }, keyHolder);

        Number key = keyHolder.getKey();

        if (Objects.isNull(key)) {
            throw new ConflictException(DirectorErrorMessages.conflict);
        }

        director.setId(key.intValue());
        return director;
    }
```

2023-01-29 10:38 UTC, Prysya requested changes

2023-01-29 10:38 UTC, Prysya commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +        int savedReviewId = Objects.requireNonNull(holder.getKey()).intValue();
Objects.requireNonNull тровнет NPE если будет null

2023-01-29 14:09 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +        int savedReviewId = Objects.requireNonNull(holder.getKey()).intValue();
Исправлено

2023-01-29 14:10 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmReview/ReviewDbStorage.java
> +        } catch (NullPointerException e) {
Сделал по аналогии

2023-01-29 14:16 UTC, Prysya approved these changes
Апрув 

![image](https://resize.yandex.net/mailservice?url=https%3A%2F%2Fcdn.letteros.com%2FletterUploads%2F25610%2Fmf87t_mf61p_congrats.gif&proxy=yes&key=68f033195ca50db61111cb9616cd8458)

2023-01-29 14:26 UTC, merged